### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by ButtaJones** [Shubhamrawat5/apple-playlist-downloader#1]
Is this still working? Would it be possible to download Apple Music videos? For example,
https://music.apple.com/ca/station/verzuz-gucci-mane-x-jeezy/ra.1539484265

I'm pretty good at finding m3u8 streams by using the inspector, would there be a way to sniff out Apple's files? The youtube-dl to download.

**Comment by Shubhamrawat5** [comment]
Yes. It still work but this is for playlist only! Not for radio stations. Basically what this does is, it extracts and make a list of all the songs for our given playlist then it download all those songs from that list one by one from a different site

**Comment by Dipanshu6** [comment]
in what format does it download songs?

**Comment by Shubhamrawat5** [comment]
mp3
