### ISSUE TITLE
Best Quality Available

### ISSUE THREAD

**Issue by adrianmejiam** [Shubhamrawat5/apple-playlist-downloader#15]
Cant download lossless  music ?

**Comment by antoinebollengier** [comment]
> Cant download lossless music ?

Hi ! Sorry, actually you can't download lossless music. But actual mp3 is in the best mp3 quality (320kps). I already think about download lossless music but for that we have to crack apple DRM algorithm... (very hard :(, but I you know how to do it make a PR ! ). The second option is to record output of your Mac (there is no lossless on iTunes Windows and on web player), but it takes a very long time (you have to listen to each track and record them manually). Others program already exists but they are not free (39$ min I remember). Here is a link : https://www.viwizard.com/apple-music-tips/remove-itunes-drm.html 
You can burn a CD too and extract tracks with clementine for example.

Hope I answered to your question !

**Comment by a1waysbeta** [comment]
Is there a way to download 256k m4a files when I have an AM subscription? I'm not looking for lossless format music, iTunes plus aac is enough.

**Comment by b5i** [comment]
> Is there a way to download 256k m4a files when I have an AM subscription? I'm not looking for lossless format music, iTunes plus aac is enough.

No, it's not possible. Apple downloads .m4p files that are protected by DRM. Actually it's not possible to decode them. The downloader used in this program gives you a full-quality mp3, even if it's not m4a. I could eventually write a little option to convert it to m4a if you want. Having Apple Music subscription is required to download those m4p files so unfortunately you cannot have Apple Music m4a's even if you are subscribed.

Hope it'll help you !

**Comment by a1waysbeta** [comment]
Thanks. No need to convert the format, it's done well enough so far, thanks for sharing.

**Comment by GreenDiscord** [comment]
Fun fact, you can crack the DRM by burning the song to a disk in Itunes or such

**Comment by b5i** [comment]
> Fun fact, you can crack the DRM by burning the song to a disk in Itunes or such

Yes I know (your remembered me thanks), it is possible to auto burn playlists and fetch the tracks. It would be great to create an extension that support a CD reader and automatically read. I'll try to work on it and I'll update this issue!
