### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tit_art' of undefined

### ISSUE THREAD

**Issue by amirnaur** [Shubhamrawat5/apple-playlist-downloader#16]
Here is what i get when trying to download my playlist: https://music.apple.com/kz/playlist/electro/pl.u-ZmblVD1CRxDlMm

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tit_art' of undefined
    at getURL (/<my_path>/music/apple-playlist-downloader/app.js:147:51)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by amirnaur** [comment]
3 AM (Original Mix) Bobby Blanco & Mikki Moto 3 Am - Single

After deleting this song from playlist, script stoped throwing error. is that because of & symb?(or idk) hope it helpes.

This song is in playlist now, so you can see the error

**Comment by Shubhamrawat5** [comment]
Thanks for putting the error, There was a issue with while loop. It is now fixed with latest commit.
