### ISSUE TITLE
Song number limit: 100

### ISSUE THREAD

**Issue by wildlighted** [Shubhamrawat5/apple-playlist-downloader#19]
Hello!

The tool works wonderfully but seems to cut off playlists at 100 songs. Some of mine are longer and while testing on them only the first 100 tracks were found and downloaded. If you could look into it it would be cool, but as it stands the tool is already a great help :)

Thanks!

**Comment by antoinebollengier** [comment]
Yeah, already seen this issue and I’ll try to fix it!

**Comment by GreenDiscord** [comment]
Any updates on this issue?

**Comment by Shubhamrawat5** [comment]
Can you share playlist URL with 100+ songs

**Comment by Shubhamrawat5** [comment]
> > Can you share playlist URL with 100+ songs
> 
> https://music.apple.com/ch/playlist/hits-des-ann%C3%A9es-80-les-indispensables/pl.af4d982795c6472ea48579eb147cd726?l=fr

okay so page shows only first 100 songs then on scroll to the end loads further tracks info. I'm not sure if we can achieve this with currently used axios and web scrapping

**Comment by b5i** [comment]
> okay so page shows only first 100 songs then on scroll to the end loads further tracks info. I'm not sure if we can achieve this with currently used axios and web scrapping

Yep, maybe scrap the request format and adapt it to the playlist ?

**Comment by b5i** [comment]
Interesting fact : Apple Music Beta web interface does not load the entire playlist but only the first 100 tracks ! 🙃

**Comment by b5i** [comment]
> Ok, Could you make a linking to the apple music api , then maybe like get the the first 100 songs, and then create a new playlist with the rest?

I'm trying to.

**Comment by Shubhamrawat5** [comment]
It should be fetching more than 100 songs now, can anyone verify?

**Comment by b5i** [comment]
> It should be fetching more than 100 songs now, can anyone verify?

It is 👍
