### ISSUE TITLE
Make it a CLI installable through npm ?

### ISSUE THREAD

**Issue by rgarrigue** [Shubhamrawat5/apple-playlist-downloader#20]
Hi there

Great work, thanks a lot :-)

Just a suggestion, for ease of use, maybe this could be made into a CLI taking the URL as argument, installable through npm ? Like

```
npm install apple-playlist-downloader
apple-playlist-downloader https://this.url
```

**Comment by b5i** [comment]
> Hi there
> 
> 
> 
> Great work, thanks a lot :-)
> 
> 
> 
> Just a suggestion, for ease of use, maybe this could be made into a CLI taking the URL as argument, installable through npm ? Like
> 
> 
> 
> ```
> 
> npm install apple-playlist-downloader
> 
> apple-playlist-downloader https://this.url
> 
> ```
> 
> 
> 
> 

Hey !
Yes this could be very nice, do you want to do it yourself and make a PR ? If not I could make it probably in a few days.
I would use my own fork if this project because this one doesn't have some update that I've made.

**Comment by rgarrigue** [comment]
Sorry I can't, I'm not much of a NodeJS dev to do that fast & I'm overloaded at work currently ;-$

**Comment by b5i** [comment]
> Sorry I can't, I'm not much of a NodeJS dev to do that fast & I'm overloaded at work currently ;-$
> 
> 

No problem! ;-)

**Comment by Shubhamrawat5** [comment]
I also thought to take playlist url from user input but not by creating a package but using some module by which we can take user input in nodejs. 

Still, we have to clone and install all packages but then need not to edit the playlist info in apple_playlist.js file like
$ node app.js https://playlist.link

**Comment by Shubhamrawat5** [comment]
I've never created any npm package so don't have any knowledge about it but yeah, I think it'll be much better and easy to use with just 2 commands
`npm install apple-playlist-downloader
apple-playlist-downloader https://this.url`

**Comment by Shubhamrawat5** [comment]
I've never created any npm package so don't have any knowledge about it but yeah, I think it'll be much better and easy to use with just 2 commands

```
npm install apple-playlist-downloader
apple-playlist-downloader https://this.url
```

**Comment by rgarrigue** [comment]
There's npx that could help  https://docs.npmjs.com/cli/v7/commands/npx

An example out there using npx https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli

**Comment by b5i** [comment]
> I've never created any npm package so don't have any knowledge about it but yeah, I think it'll be much better and easy to use with just 2 commands
> 
> 
> 
> ```
> 
> npm install apple-playlist-downloader
> 
> apple-playlist-downloader https://this.url
> 
> ```

Yes of course, maybe even cut the name and get a command like 
```
apd url

```
I'll work on it in a few days and post it on npm and on GitHub as a release. Continue to write comments if you have more ideas!

**Comment by b5i** [comment]
> I also thought to take playlist url from user input but not by creating a package but using some module by which we can take user input in nodejs.
> 
> Still, we have to clone and install all packages but then need not to edit the playlist info in apple_playlist.js file like `$ node app.js https://playlist.link`

Done in PR #21

**Comment by rgarrigue** [comment]
Thanks 🙏🏿
