### ISSUE TITLE
Songs that are not found

### ISSUE THREAD

**Issue by baptistepoligne** [Shubhamrawat5/apple-playlist-downloader#22]
Hi ! just a quick question about why some songs are not found while some are in the same album  ? Just to understand, thx !

**Comment by baptistepoligne** [comment]
Yes here is an album for exemple : System 7 - Field of Dreams
What is the website you are gathering the files from ?
Thx

**Comment by b5i** [comment]
All the song are gathered from slider.kz.
It found only some remixes and did not download the song.
<img width="1439" alt="Capture d’écran 2022-08-19 à 8 00 55 AM" src="https://user-images.githubusercontent.com/44288655/185553389-39aa7bfc-5167-43f0-8105-1c4b75d606c9.png">

**Comment by baptistepoligne** [comment]
Oh ok I understand ! Thx for the explanation
