### ISSUE TITLE
'Error: maybe the url you inserted is not of apple music playlist or check your connection!' even though link is correct

### ISSUE THREAD

**Issue by shan-shan-dar** [Shubhamrawat5/apple-playlist-downloader#24]
Hi, I cloned the directory via the https and followed the instructions.

For any playlist on apple music, I copy the link correctly and paste on line 8 in apple_playlist.js 
For all of them, however, I get 'Error: maybe the url you inserted is not of apple music playlist or check your connection!'

Thank you

**Comment by Shubhamrawat5** [comment]
Try now. It should be working now if you follow all the steps carefully

**Comment by jojo-monk** [comment]
I have exactly the same error...

**Comment by Shubhamrawat5** [comment]
@jojo-monk can you post the playlist url

**Comment by jojo-monk** [comment]
https://music.apple.com/fr/playlist/cathou/pl.u-6mo4lL8sZxqWD7

**Comment by Shubhamrawat5** [comment]
For me, It's working fine.

STARTING....

Playlist URL:  https://music.apple.com/fr/playlist/cathou/pl.u-6mo4lL8sZxqWD7
Playlist Name:
Playlist User:
Total songs:  15
==[ SONG NOT FOUND! ]== : Les beaux moments sont trop courtsFrancis Cabrel
==[ SONG NOT FOUND! ]== : Fort AlamourFrancis Cabrel
(3/15) Starting download: Bernard Lavilliers - Le cœur du monde
-> downloading [==                                      ] 4% 18.2s

**Comment by jojo-monk** [comment]
Ok, I'm going to try again tonight, what command line do you use?

I had to miss a step...

Envoyé de mon iPhone

**Comment by jojo-monk** [comment]
I understood why I have this error, it's because I installed the Apple-playlist-downloaded cli it's the one that doesn't work, indeed if I remove the cli, and I use the script alone, it works.

Thanks
