### ISSUE TITLE
What does this error mean, and how can I fix it: Error: Error: connect ECONNREFUSED ::1:80

### ISSUE THREAD

**Issue by shan-shan-dar** [Shubhamrawat5/apple-playlist-downloader#26]
Almost 50% of the songs in any playlist fail to get downloaded due to this error. The error number is -4078, and the name is 'ECONNREFUSED'.

Here is the complete error log:

![download](https://user-images.githubusercontent.com/105597557/206863632-a0263c31-a947-47b5-9984-e72f5f7a4cbc.png)

Thank you for any help!

**Comment by Shubhamrawat5** [comment]
I think, the error is from slider.kz api (from where this tool is downloading song). There are many changes in that api by its developer.

I'll be automatically fixed in few days/weeks.
