### ISSUE TITLE
Failing to download playlist, some songs result in a stack trace

### ISSUE THREAD

**Issue by sectune** [Shubhamrawat5/apple-playlist-downloader#3]
During the run of the playlist downloading it seems to me that the script encountered a search result/url which could not be downloaded because it's missing on the server? (hence the 404 error). The script doesn't ignore and continue to next song and doesn't proceed gracefully but throws a stack. Example below. Thank you once more!

(6/100) Starting download: Bahh Tee, Turken - Кто я без тебя?
(node:1350) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Library/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Library/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/Library/node_modules/axios/lib/adapters/http.js:231:9)
    at RedirectableRequest.emit (events.js:400:28)
    at RedirectableRequest._processResponse (/Library/node_modules/follow-redirects/index.js:380:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Library/node_modules/follow-redirects/index.js:56:10)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Shubhamrawat5** [comment]
Singer name have comma between them so this comma in url is causing problem. let me fix

**Comment by Shubhamrawat5** [comment]
I've added error handling blocks to ignore the broken url if comes up. It will move to next song instead of crashing.

**Comment by sectune** [comment]
it almost worked with, the skipping is fine, although the next song is not proceeded to be downloaded and it exits (this tine gracefully) with the nondescript error "some error came!":
(6/100) Starting download: Bahh Tee, Turken - Кто я без тебя?
some error came!

Thanks so much for looking into this :)

**Comment by Shubhamrawat5** [comment]
So it stopped there and didn't move to next song?

**Comment by Shubhamrawat5** [comment]
okay i found the silly mistake and i've fixed it now! Hope everything works fine now.

**Comment by sectune** [comment]
Thanks so much! You are awesome! Working now 👍
