### ISSUE TITLE
Script do not find any songs

### ISSUE THREAD

**Issue by BigFudge1998** [Shubhamrawat5/apple-playlist-downloader#30]
When I try to run the script, it does not fin any songs and return 

#### ALL SONGS ARE DOWNLOADED!! ####

Songs that are not found:-
None!

**Comment by Shubhamrawat5** [comment]
Can you share playlist url

**Comment by Shubhamrawat5** [comment]
I think apple is now dynamic loading the playlist song details, because of this web scraping is not working

**Comment by BigFudge1998** [comment]
I tried with that playlist : https://music.apple.com/be/playlist/electro/pl.u-aZb0gKZTPVoZqVR

But I also tried with public playlist and apple playlist. None of them worked. 

Good luck in your work and thank you !

**Comment by Shubhamrawat5** [comment]
Hi, It should be working now! Check once

**Comment by BigFudge1998** [comment]
Works like a charm

Thank you !
